#!/usr/bin/python3

# Python program for connecting to an imap server, starting TLS and issuing a
# select command. First use case for connection hijacking.

import imaplib, string, sys, os, re

M = imaplib.IMAP4( '10.45.1.2' );
M.starttls();
M.login( 'colm', 'colm' );

# Open the mailbox.
M.select( 'INBOX' );
f = M.response('OK')

print( f )

M.close()
M.logout()

